### ISSUE TITLE
Module requires lib_atlas to be installed !

### ISSUE THREAD

**Issue by gauthiermartin** [sonia-auv/provider_imu#1]
## Expected Behavior
 - Code should compile 

## Current Behavior
`
-- Could NOT find lib_atlas (missing: lib_atlas_DIR)
-- Could not find the required component 'lib_atlas'. The following CMake error indicates that you either need to install the package with the same name or change your environment so that it can be found.
CMake Error at /opt/ros/melodic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by "lib_atlas" with
  any of the following names:

    lib_atlasConfig.cmake
    lib_atlas-config.cmake

  Add the installation prefix of "lib_atlas" to CMAKE_PREFIX_PATH or set
  "lib_atlas_DIR" to a directory containing one of the above files.  If
  "lib_atlas" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  proc_actuators/CMakeLists.txt:44 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/sonia/ros_sonia_ws/build/CMakeFiles/CMakeOutput.log".
See also "/home/sonia/ros_sonia_ws/build/CMakeFiles/CMakeError.log".
Invoking "cmake" failed`

## Possible Solution
We need to install lib_atlas in sonia_message or in each node that requires it  

## Comments
@coumarc9 Could you take care of this 
 
## Environment Used
- Project version : 1.0.0
- docker version : 19.03.8, build afacb8b
- docker-compose version : 1.25.5, build 8a1c60f6

**Comment by supertoto29** [comment]
@alexemdesgagne Done?

**Comment by alexemdesgagne** [comment]
@supertoto29  Je sais que lib_atlas a été mis dans sonia_common. Il faut simplement s'assurer que le code compile.

**Comment by supertoto29** [comment]
@alexemdesgagne @0x72D0 Since we use the VN-100 on both platforms, I am closing this issue.
