### ISSUE TITLE
Checksum Issue with IMU

### ISSUE THREAD

**Issue by supertoto29** [sonia-auv/provider_imu#11]
**Warning :** Before creating an issue or task, make sure that it does not already exists in the [issue tracker](../). Thank you.

## Expected Behavior
The provider doesn't return a lot of bad checksum in a certain amount of time or like none. The cable has been shorten so the data should even be cleaner.

## Current Behavior
We are getting a lot of provider_imu bad checksum. 

## Possible Solution
I think its due to the checksum from 0x00 and 0x0F.
[https://stackoverflow.com/questions/5760252/how-can-i-print-0x0a-instead-of-0xa-using-cout](url)

## Environment Used
- Project version : 1.2.1
- docker version : 20.10.5
- docker-compose version : 1.28.5

**Comment by 0x72D0** [comment]
after inspection, we discovered that the bug is in the parsing of the command and seems to be happening after the migration to noetic. nothing to do with the way we decode the checksum, the package ghcr.io/sonia-auv/provider_imu/provider_imu:arm64-perception-feature-bump-package work.

**Comment by 0x72D0** [comment]
The issues was a bug in the ubuntu serial drivers, a simple apt upgrade solve the problem. A ubuntu upgrade at the beginning of the dockerfile is recommended going forward.
