### ISSUE TITLE
avoid collision in ttyUSB names

### ISSUE THREAD

**Issue by 0x72D0** [sonia-auv/provider_imu#5]
## Expected Behavior
each device need to to have a different name in /dev

## Current Behavior
each device try to be ttyUSB0

## Possible Solution
find a solution in the docker udev rules.

**Comment by supertoto29** [comment]
fixed in the docker-compose files from sonia-deploy
```
privileged: true
volumes: 
 - /dev/IMU:/dev/IMU
```
